export type EventCategory = "cine" | "teatro" | "concierto" | "popup"

export interface TicketEvent {
  id: string
  name: string
  description: string
  longDescription: string
  category: EventCategory
  image: string
  date: string
  time: string
  venue: string
  city: string
  priceInCents: number
  availableTickets: number
  featured: boolean
}

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  cine: "Cine",
  teatro: "Teatro",
  concierto: "Concierto",
  popup: "Pop Up",
}

export const CATEGORY_COLORS: Record<EventCategory, string> = {
  cine: "bg-amber-500/20 text-amber-400 border-amber-500/30",
  teatro: "bg-rose-500/20 text-rose-400 border-rose-500/30",
  concierto: "bg-sky-500/20 text-sky-400 border-sky-500/30",
  popup: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
}

export const EVENTS: TicketEvent[] = [
  {
    id: "dune-3",
    name: "Dune: Parte III",
    description: "La epica conclusion de la saga de ciencia ficcion mas ambiciosa de la decada.",
    longDescription: "Sumergete en el desenlace de la saga Dune. Paul Atreides enfrenta su destino final mientras el universo conocido se tambalea al borde del caos. Una experiencia cinematografica inmersiva con sonido Dolby Atmos y proyeccion IMAX. Dirigida por Denis Villeneuve, esta pelicula promete ser el evento cinematografico del ano con efectos visuales sin precedentes y una banda sonora magistral de Hans Zimmer.",
    category: "cine",
    image: "/events/cinema-01.jpg",
    date: "2026-03-15",
    time: "19:30",
    venue: "Cinepolis Diana",
    city: "Ciudad de Mexico",
    priceInCents: 2500,
    availableTickets: 120,
    featured: true,
  },
  {
    id: "dune-3-2",
    name: "Dune: Parte III",
    description: "La epica conclusion de la saga de ciencia ficcion mas ambiciosa de la decada.",
    longDescription: "Sumergete en el desenlace de la saga Dune. Paul Atreides enfrenta su destino final mientras el universo conocido se tambalea al borde del caos. Una experiencia cinematografica inmersiva con sonido Dolby Atmos y proyeccion IMAX. Dirigida por Denis Villeneuve, esta pelicula promete ser el evento cinematografico del ano con efectos visuales sin precedentes y una banda sonora magistral de Hans Zimmer.",
    category: "cine",
    image: "/events/cinema-01.jpg",
    date: "2026-03-16",
    time: "15:30",
    venue: "Cinepolis Santa Fe",
    city: "Ciudad de Mexico",
    priceInCents: 2500,
    availableTickets: 150,
    featured: false,
  },
  {
    id: "dune-3-3",
    name: "Dune: Parte III",
    description: "La epica conclusion de la saga de ciencia ficcion mas ambiciosa de la decada.",
    longDescription: "Sumergete en el desenlace de la saga Dune. Paul Atreides enfrenta su destino final mientras el universo conocido se tambalea al borde del caos. Una experiencia cinematografica inmersiva con sonido Dolby Atmos y proyeccion IMAX. Dirigida por Denis Villeneuve, esta pelicula promete ser el evento cinematografico del ano con efectos visuales sin precedentes y una banda sonora magistral de Hans Zimmer.",
    category: "cine",
    image: "/events/cinema-01.jpg",
    date: "2026-03-17",
    time: "21:00",
    venue: "Cinepolis Reforma",
    city: "Ciudad de Mexico",
    priceInCents: 2500,
    availableTickets: 100,
    featured: false,
  },
  {
    id: "hamlet-contemporaneo",
    name: "Hamlet Contemporaneo",
    description: "Una reinterpretacion audaz del clasico de Shakespeare con escenografia minimalista.",
    longDescription: "Esta adaptacion moderna de Hamlet transporta la tragedia shakesperiana a un contexto contemporaneo. Con una puesta en escena minimalista que utiliza proyecciones digitales y un elenco de primer nivel, esta version explora los temas eternos de la venganza, la locura y el poder politico. La direccion de escena crea una atmosfera intima que conecta al espectador directamente con el conflicto interno del principe de Dinamarca.",
    category: "teatro",
    image: "/events/teatro-01.jpg",
    date: "2026-03-22",
    time: "20:00",
    venue: "Teatro Metropolitan",
    city: "Ciudad de Mexico",
    priceInCents: 8500,
    availableTickets: 45,
    featured: true,
  },
  {
    id: "hamlet-contemporaneo-2",
    name: "Hamlet Contemporaneo",
    description: "Una reinterpretacion audaz del clasico de Shakespeare con escenografia minimalista.",
    longDescription: "Esta adaptacion moderna de Hamlet transporta la tragedia shakesperiana a un contexto contemporaneo. Con una puesta en escena minimalista que utiliza proyecciones digitales y un elenco de primer nivel, esta version explora los temas eternos de la venganza, la locura y el poder politico. La direccion de escena crea una atmosfera intima que conecta al espectador directamente con el conflicto interno del principe de Dinamarca.",
    category: "teatro",
    image: "/events/teatro-01.jpg",
    date: "2026-03-23",
    time: "20:00",
    venue: "Teatro Blanquita",
    city: "Ciudad de Mexico",
    priceInCents: 8500,
    availableTickets: 50,
    featured: false,
  },
  {
    id: "hamlet-contemporaneo-3",
    name: "Hamlet Contemporaneo",
    description: "Una reinterpretacion audaz del clasico de Shakespeare con escenografia minimalista.",
    longDescription: "Esta adaptacion moderna de Hamlet transporta la tragedia shakesperiana a un contexto contemporaneo. Con una puesta en escena minimalista que utiliza proyecciones digitales y un elenco de primer nivel, esta version explora los temas eternos de la venganza, la locura y el poder politico. La direccion de escena crea una atmosfera intima que conecta al espectador directamente con el conflicto interno del principe de Dinamarca.",
    category: "teatro",
    image: "/events/teatro-01.jpg",
    date: "2026-03-24",
    time: "19:00",
    venue: "Teatro Nacional",
    city: "Ciudad de Mexico",
    priceInCents: 8500,
    availableTickets: 40,
    featured: false,
  },
  {
    id: "noche-electronica",
    name: "Noche Electronica: ODESZA",
    description: "Un espectaculo audiovisual unico con el duo de musica electronica mas aclamado.",
    longDescription: "ODESZA regresa con su gira mundial presentando un show completamente nuevo. Con un escenario de 360 grados, visuales holograficas y un sistema de sonido envolvente, esta sera una experiencia sensorial completa. El set incluye material de su nuevo album junto con los clasicos que los catapultaron a la fama. Una noche que combinara musica electronica con arte visual de vanguardia.",
    category: "concierto",
    image: "/events/concierto-01.jpg",
    date: "2026-04-05",
    time: "21:00",
    venue: "Foro Sol",
    city: "Ciudad de Mexico",
    priceInCents: 15000,
    availableTickets: 500,
    featured: true,
  },
  {
    id: "noche-electronica-2",
    name: "Noche Electronica: ODESZA",
    description: "Un espectaculo audiovisual unico con el duo de musica electronica mas aclamado.",
    longDescription: "ODESZA regresa con su gira mundial presentando un show completamente nuevo. Con un escenario de 360 grados, visuales holograficas y un sistema de sonido envolvente, esta sera una experiencia sensorial completa. El set incluye material de su nuevo album junto con los clasicos que los catapultaron a la fama. Una noche que combinara musica electronica con arte visual de vanguardia.",
    category: "concierto",
    image: "/events/concierto-01.jpg",
    date: "2026-04-06",
    time: "21:00",
    venue: "Palacio de los Deportes",
    city: "Ciudad de Mexico",
    priceInCents: 15000,
    availableTickets: 400,
    featured: false,
  },
  {
    id: "noche-electronica-3",
    name: "Noche Electronica: ODESZA",
    description: "Un espectaculo audiovisual unico con el duo de musica electronica mas aclamado.",
    longDescription: "ODESZA regresa con su gira mundial presentando un show completamente nuevo. Con un escenario de 360 grados, visuales holograficas y un sistema de sonido envolvente, esta sera una experiencia sensorial completa. El set incluye material de su nuevo album junto con los clasicos que los catapultaron a la fama. Una noche que combinara musica electronica con arte visual de vanguardia.",
    category: "concierto",
    image: "/events/concierto-01.jpg",
    date: "2026-04-07",
    time: "20:00",
    venue: "Auditorio Nacional",
    city: "Ciudad de Mexico",
    priceInCents: 15000,
    availableTickets: 350,
    featured: false,
  },
  {
    id: "arte-inmersivo",
    name: "Arte Inmersivo: Luces del Futuro",
    description: "Una exposicion interactiva que fusiona arte digital con experiencias sensoriales.",
    longDescription: "Luces del Futuro es una experiencia inmersiva que transforma un espacio industrial en un universo de arte digital interactivo. Mas de 20 instalaciones creadas por artistas internacionales responden al movimiento y la presencia del visitante. Desde tuneles de luz infinita hasta salas de proyeccion 360, cada espacio ofrece una experiencia unica. Incluye zona gastronómica con cocteleria tematica y musica ambient en vivo.",
    category: "popup",
    image: "/events/popup-01.jpg",
    date: "2026-04-12",
    time: "18:00",
    venue: "Nave Creativa",
    city: "Ciudad de Mexico",
    priceInCents: 6500,
    availableTickets: 200,
    featured: false,
  },
  {
    id: "arte-inmersivo-2",
    name: "Arte Inmersivo: Luces del Futuro",
    description: "Una exposicion interactiva que fusiona arte digital con experiencias sensoriales.",
    longDescription: "Luces del Futuro es una experiencia inmersiva que transforma un espacio industrial en un universo de arte digital interactivo. Mas de 20 instalaciones creadas por artistas internacionales responden al movimiento y la presencia del visitante. Desde tuneles de luz infinita hasta salas de proyeccion 360, cada espacio ofrece una experiencia unica. Incluye zona gastronómica con cocteleria tematica y musica ambient en vivo.",
    category: "popup",
    image: "/events/popup-01.jpg",
    date: "2026-04-13",
    time: "18:00",
    venue: "Espacios Abiertos",
    city: "Ciudad de Mexico",
    priceInCents: 6500,
    availableTickets: 250,
    featured: false,
  },
  {
    id: "arte-inmersivo-3",
    name: "Arte Inmersivo: Luces del Futuro",
    description: "Una exposicion interactiva que fusiona arte digital con experiencias sensoriales.",
    longDescription: "Luces del Futuro es una experiencia inmersiva que transforma un espacio industrial en un universo de arte digital interactivo. Mas de 20 instalaciones creadas por artistas internacionales responden al movimiento y la presencia del visitante. Desde tuneles de luz infinita hasta salas de proyeccion 360, cada espacio ofrece una experiencia unica. Incluye zona gastronómica con cocteleria tematica y musica ambient en vivo.",
    category: "popup",
    image: "/events/popup-01.jpg",
    date: "2026-04-14",
    time: "17:00",
    venue: "Centro Cultural",
    city: "Ciudad de Mexico",
    priceInCents: 6500,
    availableTickets: 180,
    featured: false,
  },
  {
    id: "matrix-resurreccion",
    name: "Matrix: La Resurreccion Final",
    description: "La ultima entrega de la saga que redefinio el cine de ciencia ficcion.",
    longDescription: "Neo regresa una vez mas en esta conclusion epica de la saga Matrix. Con efectos visuales revolucionarios y una narrativa que cuestiona los limites entre realidad y simulacion, esta pelicula lleva la franquicia a nuevas alturas. Disfruta la experiencia en pantalla IMAX con sonido inmersivo que te transportara directamente dentro de la Matrix.",
    category: "cine",
    image: "/events/cinema-02.jpg",
    date: "2026-04-20",
    time: "20:00",
    venue: "Cineteca Nacional",
    city: "Ciudad de Mexico",
    priceInCents: 2000,
    availableTickets: 80,
    featured: false,
  },
  {
    id: "matrix-resurreccion-2",
    name: "Matrix: La Resurreccion Final",
    description: "La ultima entrega de la saga que redefinio el cine de ciencia ficcion.",
    longDescription: "Neo regresa una vez mas en esta conclusion epica de la saga Matrix. Con efectos visuales revolucionarios y una narrativa que cuestiona los limites entre realidad y simulacion, esta pelicula lleva la franquicia a nuevas alturas. Disfruta la experiencia en pantalla IMAX con sonido inmersivo que te transportara directamente dentro de la Matrix.",
    category: "cine",
    image: "/events/cinema-02.jpg",
    date: "2026-04-21",
    time: "18:30",
    venue: "Cinepolis Polanco",
    city: "Ciudad de Mexico",
    priceInCents: 2000,
    availableTickets: 120,
    featured: false,
  },
  {
    id: "matrix-resurreccion-3",
    name: "Matrix: La Resurreccion Final",
    description: "La ultima entrega de la saga que redefinio el cine de ciencia ficcion.",
    longDescription: "Neo regresa una vez mas en esta conclusion epica de la saga Matrix. Con efectos visuales revolucionarios y una narrativa que cuestiona los limites entre realidad y simulacion, esta pelicula lleva la franquicia a nuevas alturas. Disfruta la experiencia en pantalla IMAX con sonido inmersivo que te transportara directamente dentro de la Matrix.",
    category: "cine",
    image: "/events/cinema-02.jpg",
    date: "2026-04-22",
    time: "19:00",
    venue: "Cinepolis Acoxpa",
    city: "Ciudad de Mexico",
    priceInCents: 2000,
    availableTickets: 90,
    featured: false,
  },
  {
    id: "el-lago-cisnes",
    name: "El Lago de los Cisnes",
    description: "La obra maestra del ballet clasico interpretada por el Ballet Nacional.",
    longDescription: "El Ballet Nacional presenta su version magistral de El Lago de los Cisnes de Tchaikovsky. Con coreografia renovada que respeta la tradicion clasica mientras incorpora elementos contemporaneos, esta produccion cuenta con un elenco de 40 bailarines, vestuario diseñado por artistas de renombre y una orquesta en vivo de 60 musicos. Una experiencia que combina la elegancia del ballet clasico con la grandeza de una produccion moderna.",
    category: "teatro",
    image: "/events/teatro-02.jpg",
    date: "2026-05-03",
    time: "19:00",
    venue: "Palacio de Bellas Artes",
    city: "Ciudad de Mexico",
    priceInCents: 12000,
    availableTickets: 30,
    featured: false,
  },
  {
    id: "el-lago-cisnes-2",
    name: "El Lago de los Cisnes",
    description: "La obra maestra del ballet clasico interpretada por el Ballet Nacional.",
    longDescription: "El Ballet Nacional presenta su version magistral de El Lago de los Cisnes de Tchaikovsky. Con coreografia renovada que respeta la tradicion clasica mientras incorpora elementos contemporaneos, esta produccion cuenta con un elenco de 40 bailarines, vestuario diseñado por artistas de renombre y una orquesta en vivo de 60 musicos. Una experiencia que combina la elegancia del ballet clasico con la grandeza de una produccion moderna.",
    category: "teatro",
    image: "/events/teatro-02.jpg",
    date: "2026-05-04",
    time: "18:00",
    venue: "Teatro Universitario",
    city: "Ciudad de Mexico",
    priceInCents: 12000,
    availableTickets: 50,
    featured: false,
  },
  {
    id: "el-lago-cisnes-3",
    name: "El Lago de los Cisnes",
    description: "La obra maestra del ballet clasico interpretada por el Ballet Nacional.",
    longDescription: "El Ballet Nacional presenta su version magistral de El Lago de los Cisnes de Tchaikovsky. Con coreografia renovada que respeta la tradicion clasica mientras incorpora elementos contemporaneos, esta produccion cuenta con un elenco de 40 bailarines, vestuario diseñado por artistas de renombre y una orquesta en vivo de 60 musicos. Una experiencia que combina la elegancia del ballet clasico con la grandeza de una produccion moderna.",
    category: "teatro",
    image: "/events/teatro-02.jpg",
    date: "2026-05-05",
    time: "19:30",
    venue: "Teatro Aldama",
    city: "Ciudad de Mexico",
    priceInCents: 12000,
    availableTickets: 35,
    featured: false,
  },
  {
    id: "festival-jazz",
    name: "Festival de Jazz Nocturno",
    description: "Una noche intima con los mejores exponentes del jazz contemporaneo.",
    longDescription: "El Festival de Jazz Nocturno reune a los artistas mas destacados del jazz contemporaneo en un formato intimo y exclusivo. Tres escenarios simultáneos ofrecen desde jazz clasico hasta fusion experimental. El evento incluye catas de vino, gastronomia gourmet y sesiones de improvisacion que hacen cada noche irrepetible. Un oasis musical para los amantes del buen jazz.",
    category: "concierto",
    image: "/events/concierto-02.jpg",
    date: "2026-05-10",
    time: "20:30",
    venue: "Lunario del Auditorio",
    city: "Ciudad de Mexico",
    priceInCents: 9500,
    availableTickets: 150,
    featured: false,
  },
  {
    id: "festival-jazz-2",
    name: "Festival de Jazz Nocturno",
    description: "Una noche intima con los mejores exponentes del jazz contemporaneo.",
    longDescription: "El Festival de Jazz Nocturno reune a los artistas mas destacados del jazz contemporaneo en un formato intimo y exclusivo. Tres escenarios simultáneos ofrecen desde jazz clasico hasta fusion experimental. El evento incluye catas de vino, gastronomia gourmet y sesiones de improvisacion que hacen cada noche irrepetible. Un oasis musical para los amantes del buen jazz.",
    category: "concierto",
    image: "/events/concierto-02.jpg",
    date: "2026-05-11",
    time: "20:00",
    venue: "Foro Indie Rocks",
    city: "Ciudad de Mexico",
    priceInCents: 9500,
    availableTickets: 200,
    featured: false,
  },
  {
    id: "festival-jazz-3",
    name: "Festival de Jazz Nocturno",
    description: "Una noche intima con los mejores exponentes del jazz contemporaneo.",
    longDescription: "El Festival de Jazz Nocturno reune a los artistas mas destacados del jazz contemporaneo en un formato intimo y exclusivo. Tres escenarios simultáneos ofrecen desde jazz clasico hasta fusion experimental. El evento incluye catas de vino, gastronomia gourmet y sesiones de improvisacion que hacen cada noche irrepetible. Un oasis musical para los amantes del buen jazz.",
    category: "concierto",
    image: "/events/concierto-02.jpg",
    date: "2026-05-12",
    time: "21:00",
    venue: "Gran Sala del Auditorio",
    city: "Ciudad de Mexico",
    priceInCents: 9500,
    availableTickets: 180,
    featured: false,
  },
  {
    id: "mercado-nocturno",
    name: "Mercado Nocturno Gastronomico",
    description: "Un festival culinario con los mejores chefs y food trucks de la ciudad.",
    longDescription: "El Mercado Nocturno Gastronomico transforma un espacio al aire libre en el paraiso de los foodlovers. Mas de 30 puestos y food trucks ofrecen lo mejor de la gastronomia local e internacional. Desde tacos gourmet hasta cocina fusion asiatica, cada bocado es una aventura. Complementado con musica en vivo, cocteleria artesanal y talleres de cocina interactivos. Un evento para disfrutar con todos los sentidos.",
    category: "popup",
    image: "/events/popup-02.jpg",
    date: "2026-05-17",
    time: "17:00",
    venue: "Explanada del Monumento",
    city: "Ciudad de Mexico",
    priceInCents: 3500,
    availableTickets: 300,
    featured: false,
  },
  {
    id: "mercado-nocturno-2",
    name: "Mercado Nocturno Gastronomico",
    description: "Un festival culinario con los mejores chefs y food trucks de la ciudad.",
    longDescription: "El Mercado Nocturno Gastronomico transforma un espacio al aire libre en el paraiso de los foodlovers. Mas de 30 puestos y food trucks ofrecen lo mejor de la gastronomia local e internacional. Desde tacos gourmet hasta cocina fusion asiatica, cada bocado es una aventura. Complementado con musica en vivo, cocteleria artesanal y talleres de cocina interactivos. Un evento para disfrutar con todos los sentidos.",
    category: "popup",
    image: "/events/popup-02.jpg",
    date: "2026-05-18",
    time: "17:00",
    venue: "Parque Hundido",
    city: "Ciudad de Mexico",
    priceInCents: 3500,
    availableTickets: 350,
    featured: false,
  },
  {
    id: "mercado-nocturno-3",
    name: "Mercado Nocturno Gastronomico",
    description: "Un festival culinario con los mejores chefs y food trucks de la ciudad.",
    longDescription: "El Mercado Nocturno Gastronomico transforma un espacio al aire libre en el paraiso de los foodlovers. Mas de 30 puestos y food trucks ofrecen lo mejor de la gastronomia local e internacional. Desde tacos gourmet hasta cocina fusion asiatica, cada bocado es una aventura. Complementado con musica en vivo, cocteleria artesanal y talleres de cocina interactivos. Un evento para disfrutar con todos los sentidos.",
    category: "popup",
    image: "/events/popup-02.jpg",
    date: "2026-05-19",
    time: "18:00",
    venue: "Paseo de la Reforma",
    city: "Ciudad de Mexico",
    priceInCents: 3500,
    availableTickets: 280,
    featured: false,
  },
]

export function getEventById(id: string): TicketEvent | undefined {
  return EVENTS.find((event) => event.id === id)
}

export function getEventsByCategory(category: EventCategory): TicketEvent[] {
  return EVENTS.filter((event) => event.category === category)
}

export function getFeaturedEvents(): TicketEvent[] {
  return EVENTS.filter((event) => event.featured)
}

export function formatPrice(priceInCents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(priceInCents / 100)
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr + "T00:00:00Z")
  return new Intl.DateTimeFormat("es-MX", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  }).format(date)
}

export function formatShortDate(dateStr: string): string {
  const date = new Date(dateStr + "T00:00:00Z")
  return new Intl.DateTimeFormat("es-MX", {
    day: "numeric",
    month: "short",
    timeZone: "UTC",
  }).format(date)
}
